AppForm/urls.py
from django.conf.urls import url
from AppForm.views import new_mess, mess_detail,edit_mess, mess_list

app_name = 'forum'
urlpatterns = [
    url(r'^$', mess_list, name='mess_list'),
    url(r'^new/', new_mess, name='new_mess'),
    url(r'^message/(?P<pk>[0-9]+)/edit/', edit_mess, name='edit_mess'),
    url(r'^message/(?P<pk>[0-9]+)/$',mess_detail, name='mess_detail')
]

FormLesson/urls.py
from django.conf.urls import url
from FormLesson.views import func_lesson

app_name = 'lesson'
urlpatterns = [
    url(r'^contact/$', func_lesson, name='form_send'),

]

HomeForm/urls.py
from django.contrib import admin
from django.urls import path,include
from register.views import index, index1


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppForm.urls', namespace='forum')),
    path('', include('FormLesson.urls', namespace='form')),
    path('', include('register.urls', namespace='register')),
    path('', index),
    path('', index1),

]

register/urls.py
from django.urls import path

from register.views import signup, log, user_logout, index

app_name = 'register'

urlpatterns = [
    path('register/', signup, name='signup'),
    path('login/', log, name='login'),
    path('logout/', user_logout, name='logout'),
    path('',index),
]

AppForm/models.py
from django.db import models
from django.utils import timezone


class Message(models.Model):
    class Meta():
        db_table = 'HomeTable'

    author = models.ForeignKey('auth.User', on_delete=True)
    mes_title = models.CharField(max_length=128, blank=False)
    mes_text = models.TextField(max_length=342, blank=False)
    mes_created_date = models.DateTimeField(default=timezone.now)
    mes_public_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.mes_title

FormLesson/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

AppForm/forms.py
from django import forms
from AppForm.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = [
            'mes_title',
            'mes_text',
        ]

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Введіть ім`я')
    last_name = forms.CharField(max_length=30, required=False, help_text='Введіть прізвище')
    email = forms.EmailField(max_length=254, help_text='Введіть емейл')
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

AppForm/views.py
from django.shortcuts import render, get_object_or_404,redirect,render_to_response
from AppForm.models import Message
from AppForm.forms import MessageForm


def mess_list(request):
    go = Message.objects.all()
    return render_to_response('all.html', {'go':go})


def mess_detail(request, pk):
    mess = get_object_or_404(Message, pk=pk)
    return render(request, 'general.html', {'mess':mess})


def new_mess(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            mess = form.save(commit=False)
            mess.author = request.user
            mess.save()
            return redirect('forum:mess_detail', pk=mess.pk)
    else:
        form = MessageForm

    return render(request,'new_message.html', {'form': form})

def edit_mess(request, pk):
    mess = get_object_or_404(Message, pk=pk)
    if request.method == 'POST':
        form = MessageForm(request.POST, instance=mess)
        if form.is_valid():
            mess = form.save(commit=False)
            mess.author = request.user
            mess.save()
        return redirect('forum:mess_detail', pk=mess.pk)
    else:
        form = MessageForm(instance=mess)
    return render(request, 'new_message.html', {'form': form})

FormLesson/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def func_lesson(request):
    errors = []
    form = {}

    if request.POST:
        form['name'] = request.POST.get('name')
        form['email'] = request.POST.get('email')
        form['message'] = request.POST.get('message')

        if not form['name']:
            errors.append('Введіть коректно ім`я')
        if '@' not in form['email']:
            errors.append('Введіть коректно емейл')
        if not form['message']:
            errors.append('Поле повідомлення не заповнено')

        if not errors:
            return HttpResponse('Дякую, ваше повідомлення заповнено')
    return render(request,'lesson.html',{'errors':errors, 'form':form},)

register/views.py
from django.contrib import auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render_to_response, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader, RequestContext
from django.template.context_processors import csrf
from django.contrib.auth import login, authenticate

from register.forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('base.html')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def log(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            args['login_error'] = 'Логін введено невірно.'
            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def index(request):
    return render_to_response( {'username': auth.get_user(request).username})

def index1(request):
    return render_to_response('navbar.html', {'username': auth.get_user(request).username})


# не працює


# def index(request):
#     template = loader.get_template('base.html')
#     c = {
#         'username': auth.get_user(request).username
#     }
#     return HttpResponse(template.render(c, request))

# def index(request):
#     template = loader.get_template('base.html')
#     c = RequestContext(request,{
#         'username': auth.get_user(request).username
#     })
#     return HttpResponse(template.render(c, request))

AppForm/templates/all.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block message %}
<div class="alert alert-info">
<div class="div">
    <button type="button" class="btn btn-warning">
        <a href="{% url 'forum:new_mess' %}">Нове повідомлення</a><br>
    </button>
</div>
     <br>
<div class="alert alert-success">
{% for go in go %}
  Автор : {{ go.author }}
<h3><a href="{% url 'forum:mess_detail' go.pk%}">{{ go.mes_title  }}</a></h3>
    {{ go.mes_text }}     <br>
     <br>
    Дата: {{ go.mes_created_date }}<br>
     <br>
        <a href="{% url 'forum:edit_mess' pk=go.pk %}" class="glyphicon glyphicon-repeat"></a> редагувати
     <hr>
    {% endfor %}
</div>
</div>


    <link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />

{% endblock %}

AppForm/templates/general.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block message %}
        <a href="{% url 'forum:edit_mess' pk=mess.pk %}" class="glyphicon glyphicon-repeat"></a>

<div class="mess">
    <a href=""></a>
{% if mess.mes_created_date %}
    <div class="date">
        {{ mess.mes_created_date }}
    </div>
{% endif %}

    {{ mess.mes_title }}
    {{ mess.mes_text|linebreaks }}
</div>
<a href="{% url 'forum:mess_list' %}">Всі записи</a>
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />
{% endblock %}

AppForm/templates/golovna.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block text %}
<div align="center">
    <div class="jumbotron" align="center">
        <div class="alert alert-success">
            <h1>Пишу на звязці Python/Django/Bootstrap</h1>
        </div>
    </div>
</div>
{% endblock %}

AppForm/templates/new_message.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block message %}
<form method="post">
{% csrf_token %}
    <p>{{ user }} введіть повідомлення:</p>
    {{ form.as_p }}
    <input type="submit" value="відправити">
</form>


<link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />
{% endblock %}

FormLesson/templates/lesson.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block message %}

{% if errors %}

    {% for error in errors %}
       <div class="alert alert-danger"> {{ error }}</div>
    {% endfor %}

{% endif %}<br>

 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Зворотній зв'зок</h2>
  </div>
  <div class="panel-body">
<div class="well well-lg">
    <h3></h3>
    <form action="/contact/" method="post">{% csrf_token %}
        <input class="form-control" placeholder="Введіть ім'я" name="name"  type="text" value="{{ form.name }}"><br>
        <input class="form-control" placeholder="Введіть email" name="email" type="text" value="{{ form.email }}"><br>
        <textarea class="form-control" placeholder="Введіть ваше повідомлення" cols = '40'  name="message">{{ form.message }}</textarea><br>

    <input type="submit" value="Послать сообщение">

    </form>
</div>

<link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />



{% endblock %}

register/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block login %}


 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Вхід</h2>
  </div>
  <div class="panel-body">
<div class="well well-lg">
    <h3></h3>
<form action="/login/" method="post">
    {% csrf_token %}
    <label for="username">Ім'я користувача</label>
    <input class="form-control" type="text" name="username" id="username"><br>
    <label for="password">Пароль</label>
    <input class="form-control" type="password" name="password" id="password"><br>
    <input class="button" type="submit" value="Войти">
    {% if login_error %}
        <label class="error">{{ login_error }}</label>
    {% endif %}

</form><br>
        <link rel="stylesheet" type="text/css" href="{% static "css/my_style.css" %}" />
{% endblock %}

register/templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block universal %}

  <form method="post">
    {% csrf_token %}
    {% for field in form %}

      <p>

        {{ field|bootstrap_horizontal }}
        {% for error in field.errors %}
            {{ error|bootstrap_horizontal }}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-group-sm" type="submit">Sign up</button>
  </form>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <title>Forum</title>
</head>
<body>
{% include 'navbar.html' %}

{% if username %}
    <li><a href="/logout/"><span class="glyphicon glyphicon-user"></span> Выйти ({{ username }})</a></li>
{% else %}
    <li><a href="/login/"><span class="glyphicon glyphicon-user"></span> Войти</a></li>
{% endif %}

{{ username }}

<div class="jumbotron">
<div class="container">
    <main class="row">
        <article class="col-sm-12 col-md-8 col-lg-9">
        <div align="center">
        <div class="jumbotron" align="center">
            <div class="alert alert-success">
                <h1>Python/Django/Bootstrap</h1>
            </div>
        </div>
</div>
    {% block message %}
    {% endblock %}
        {% block universal %}
        {% endblock %}
        {% block login %}
        {% endblock %}
        </article>
        <aside class="col-sm-12 col-md-4 col-lg-3">
            <!--Ряд, блок с классом row-->
            <div class="row">
              <!--Адаптивный блок 1-->
              <div class="col-sm-6 col-md-12">
                <!--Содержимое-->
              </div>
              <!--Адаптивный блок 2-->
              <div class="col-sm-6 col-md-12">
                <!--Содержимое-->
            <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm"><!-- Адаптивная разметка для мобильных устройств-->
<div class="list-group">
  <a href="#" class="list-group-item active list-group-item-success">
    Категорії
  </a>
      <a href="/blog/catlist/" class="list-group-item" data-toggle="tooltip" title="Список категорий">Список категорій</a>
      <a href="/blog/category/django/" class="list-group-item" data-toggle="tooltip" title="Рубрика об Django">Django</a>
      <a href="/blog/category/python/" class="list-group-item" data-toggle="tooltip" title="Рубрика об Python">Python</a>
      <a href="/blog/category/pycharm/" class="list-group-item" data-toggle="tooltip" title="Рубрика об Pycharm">Pycharm</a>
      <a href="/blog/category/mysql/" class="list-group-item" data-toggle="tooltip" title="Рубрика об MySql">MySql</a>
      <a href="/blog/category/apache/" class="list-group-item" data-toggle="tooltip" title="Рубрика об Apache">Apache</a>

      <a href="/upload/" class="list-group-item" data-toggle="tooltip" title="Загрузка файлов">Загрузка файлов <span class="label label-success">Обновлено</span></a>


</div>



<div class="list-group">
  <a href="#" class="list-group-item active list-group-item-success">
  Сторінки без баз даних
  </a>
      <a href="/" class="list-group-item">Главная</a>
      <a href="/info/aboutme/" class="list-group-item" data-toggle="tooltip" title="Кто мы?">О нас</a>
      <a href="/info/pay/" class="list-group-item" data-toggle="tooltip" title="Оплата товара">Оплата</a>
      <a href="/info/aboutproject/" class="list-group-item" data-toggle="tooltip" title="Все что касается нашего портала">О проекте</a>
      <a href="/info/news/" class="list-group-item" data-toggle="tooltip" title="Раздел с новостями сайта">Новости</a>
</div>

<div class="list-group">
  <a href="#" class="list-group-item active list-group-item-success">
  Сторінки з базами даних
  </a>
      <a href="/info/rabota/" class="list-group-item" data-toggle="tooltip" title="Примеры наших работ">Наша работа</a>
      <a href="/info/helping/" class="list-group-item" data-toggle="tooltip" title="Поддержка">Помощь</a>
      <a href="/info/rules/" class="list-group-item" data-toggle="tooltip" title="Правила портала">Правила</a>
      <a href="/info/commodity/" class="list-group-item" data-toggle="tooltip" title="Наш товар">Товар</a>
      <a href="/info/closeout/" class="list-group-item" data-toggle="tooltip" title="Рспродажа товаров по низким ценам">Распродажа</a>
      <a href="/info/slider/" class="list-group-item" data-toggle="tooltip" title="Слайдер">Слайдер</a>
</div>

<div class="list-group">
  <a href="#" class="list-group-item active list-group-item-success">
  Додаткові сторінки
  </a>
      <a href="#" class="list-group-item" data-toggle="tooltip" title="Блог на моем практикуме!">Практикум извлечение записи из базы данных по id - Блог!</a>
      <a href="/info/order/" class="list-group-item" data-toggle="tooltip" title="Работа с базой данных">Выборка из базы</a>
      <a href="/forms/" class="list-group-item" data-toggle="tooltip" title="Очень простая форма">Форма1</a>
      <a href="/forms2/" class="list-group-item" data-toggle="tooltip" title="Чуть сложнее форма">Форма2</a>
      <a href="/forms3/" class="list-group-item" data-toggle="tooltip" title="Совсем сложная форма">Форма3</a>
      <a href="/blog/time/1/" class="list-group-item" data-toggle="tooltip" title="Вывод даты и времени">Дата и время - пример</a>
      <a href="/blog/gtx/" class="list-group-item" data-toggle="tooltip" title="Всякие разнае страницы!">Просто страница! </a>
</div>
</nav>
              </div>
            </div>
        </aside>
    </main>
</div>



</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>

templates/navbar.html
{% load staticfiles %}


<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a class="navbar-brand" href="#">Forum</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'forum:mess_list' %}">Всі пости</a></li>
          <li><a href="{% url 'form:form_send' %}">Зворотній звязок</a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Дії<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'forum:new_mess' %}">Добавити</a></li>
            <li class="divider"></li>
            <li><a href="#">Отдельная ссылка</a></li>
            <li class="divider"></li>
            <li><a href="#">Еще одна отдельная ссылка</a></li>
          </ul>
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if username %}
        <li><a href="{% url 'register:login' %}">Ввійти</a></li>
        {% else %}
        <li><a href="{% url 'register:login' %}">Ввійти</a></li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Дії <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'register:signup' %}">Реєстрація</a></li>
              {% if username %}
            <li><a href="{% url 'register:logout' %}">Вийти {{ username }}</a></li>
              {% else %}
              <li><a href="{% url 'register:login' %}">Ввійти</a></li>
              {% endif %}
            <li><a href="#">Что-то еще</a></li>
            <li class="divider"></li>
            <li><a href="#">Отдельная ссылка</a></li>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>